FROM python:3.11-slim-bookworm

# Install Java + procps
RUN apt-get update && apt-get install -y openjdk-17-jdk procps && rm -rf /var/lib/apt/lists/*

# Set JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

# Install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

WORKDIR /app
COPY . .

ARG POSTGRES_USER
# ARG POSTGRES_PASSWORD
ARG POSTGRES_DB
ARG POSTGRES_HOST
ARG POSTGRES_PORT
ARG POSTGRES_TABLE
ARG POSTGRES_HISTORY_TABLE
ARG POSTGRESS_TABLE_PKID
ARG POSTGRES_DRIVER
ARG POSTGRES_URL
ARG TARGET_DB
ARG KAFKA_BOOTSTRAP_SERVERS
ARG KAFKA_TOPIC
ARG CHECKPOINT_LOC

ENV POSTGRES_USER=$POSTGRES_USER \
    # POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
    POSTGRES_DB=$POSTGRES_DB \
    POSTGRES_HOST=$POSTGRES_HOST \
    POSTGRES_PORT=$POSTGRES_PORT \
    POSTGRES_TABLE=$POSTGRES_TABLE \
    POSTGRES_HISTORY_TABLE=$POSTGRES_HISTORY_TABLE \
    POSTGRESS_TABLE_PKID=$POSTGRESS_TABLE_PKID \
    POSTGRES_DRIVER=$POSTGRES_DRIVER \
    POSTGRES_URL=$POSTGRES_URL \
    TARGET_DB=$TARGET_DB \
    KAFKA_BOOTSTRAP_SERVERS=$KAFKA_BOOTSTRAP_SERVERS \
    KAFKA_TOPIC=$KAFKA_TOPIC \
    CHECKPOINT_LOC=$CHECKPOINT_LOC

EXPOSE 5000
# ENTRYPOINT ["python"]
CMD ["python run.py"]
